[functions.decompose-requirements]
verify_jwt = false

[functions.expand-requirement]
verify_jwt = false

[functions.verify-admin]
verify_jwt = false

[functions.expand-standards]
verify_jwt = false

[functions.generate-specification]
verify_jwt = false

[functions.ai-create-standards]
verify_jwt = false