[functions.decompose-requirements]
verify_jwt = false

[functions.expand-requirement]
verify_jwt = false

[functions.verify-admin]
verify_jwt = false

[functions.expand-standards]
verify_jwt = false

[functions.generate-specification]
verify_jwt = false

[functions.ai-create-standards]
verify_jwt = false

[functions.create-project]
verify_jwt = false

[functions.ai-architect]
verify_jwt = false

[functions.ai-architect-critic]
verify_jwt = false

[functions.chat-stream-gemini]
verify_jwt = false

[functions.chat-stream-anthropic]
verify_jwt = false

[functions.chat-stream-xai]
verify_jwt = false

[functions.summarize-artifact]
verify_jwt = false

[functions.summarize-chat]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.upload-artifact-image]
verify_jwt = false